-- ippado.IDS definition

CREATE TABLE `IDS` (
  `TABLE_NAME` varchar(20) NOT NULL,
  `NEXT_ID` decimal(30,0) NOT NULL DEFAULT 0,
  PRIMARY KEY (`TABLE_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='IDS';


-- ippado.IPD_AUTHOR definition

CREATE TABLE `IPD_AUTHOR` (
  `AUTHOR_CODE` varchar(30) NOT NULL DEFAULT '' COMMENT '권한코드',
  `AUTHOR_NM` varchar(60) NOT NULL COMMENT '권한명',
  `AUTHOR_DC` varchar(200) DEFAULT NULL COMMENT '권한설명',
  `AUTHOR_CREAT_DE` char(20) NOT NULL COMMENT '권한생성일',
  PRIMARY KEY (`AUTHOR_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='권한정보';


-- ippado.IPD_CL_CODE definition

CREATE TABLE `IPD_CL_CODE` (
  `CL_CODE` char(3) NOT NULL COMMENT '분류코드',
  
  `CL_CODE_NM` varchar(60) DEFAULT NULL COMMENT '분류코드명',
  `CL_CODE_DC` varchar(200) DEFAULT NULL COMMENT '분류코드설명',
  `USE_AT` char(1) DEFAULT NULL COMMENT '사용여부',
  `FRST_REGIST_PNTTM` datetime DEFAULT NULL COMMENT '최초등록시점',
  `FRST_REGISTER_ID` varchar(20) DEFAULT NULL COMMENT '최초등록자ID',
  `LAST_UPDT_PNTTM` datetime DEFAULT NULL COMMENT '최종수정시점',
  `LAST_UPDUSR_ID` varchar(20) DEFAULT NULL COMMENT '최종수정자ID',
  PRIMARY KEY (`CL_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='공통분류코드';


-- ippado.IPD_GROUP definition

CREATE TABLE `IPD_GROUP` (
  `GROUP_ID` char(20) NOT NULL DEFAULT '' COMMENT '그룹ID',
  `GROUP_NM` varchar(60) NOT NULL COMMENT '그룹명',
  `GROUP_CREAT_DE` char(20) NOT NULL COMMENT '그룹생성일',
  `GROUP_DC` varchar(100) DEFAULT NULL COMMENT '그룹설명',
  PRIMARY KEY (`GROUP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='권한그룹정보';


-- ippado.IPD_LOGIN_LOG definition

CREATE TABLE `IPD_LOGIN_LOG` (
  `LOG_ID` char(20) NOT NULL COMMENT '로그ID',
  `CONECT_ID` varchar(20) DEFAULT NULL COMMENT '접속ID',
  `CONECT_IP` varchar(23) DEFAULT NULL COMMENT '접속IP',
  `CONECT_MTHD` char(4) DEFAULT NULL COMMENT '접속방식',
  `ERROR_OCCRRNC_AT` char(1) DEFAULT NULL COMMENT '오류발생여부',
  `ERROR_CODE` char(3) DEFAULT NULL COMMENT '오류코드',
  `CREAT_DT` datetime DEFAULT NULL COMMENT '생성일시',
  PRIMARY KEY (`LOG_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='접속로그';


-- ippado.IPD_LOGIN_POLICY definition

CREATE TABLE `IPD_LOGIN_POLICY` (
  `USER_ID` varchar(20) NOT NULL DEFAULT '' COMMENT '사용자ID',
  `IP_INFO` varchar(23) NOT NULL COMMENT 'IP정보',
  `DPLCT_PERM_AT` char(1) NOT NULL COMMENT '중복허용여부',
  `LMTT_AT` char(1) NOT NULL COMMENT '제한여부',
  `FRST_REGISTER_ID` varchar(20) DEFAULT NULL COMMENT '최초등록자ID',
  `FRST_REGIST_PNTTM` datetime DEFAULT NULL COMMENT '최초등록시점',
  `LAST_UPDUSR_ID` varchar(20) DEFAULT NULL COMMENT '최종수정자ID',
  `LAST_UPDT_PNTTM` datetime DEFAULT NULL COMMENT '최종수정시점',
  PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='로그인정책';


-- ippado.IPD_MBER_HISTORY definition

CREATE TABLE `IPD_MBER_HISTORY` (
  `USER_ID` varchar(20) NOT NULL,
  `CHANGE_DE` datetime NOT NULL,
  `GROUP_ID` char(20) DEFAULT NULL,
  `MBTLNUM` varchar(20) DEFAULT NULL,
  `EMAIL_ADRES` varchar(50) DEFAULT NULL,
  `USER_STTUS_CODE` varchar(15) DEFAULT NULL,
  PRIMARY KEY (`USER_ID`,`CHANGE_DE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- ippado.IPD_PROGRMS definition

CREATE TABLE `IPD_PROGRMS` (
  `PROGRAM_ID` varchar(10) NOT NULL COMMENT '프로그램아이디',
  `PROGRM_FILE_NM` varchar(60) NOT NULL DEFAULT '' COMMENT '프로그램파일명',
  `PROGRM_STRE_PATH` varchar(100) NOT NULL COMMENT '프로그램저장경로',
  `PROGRM_KOREAN_NM` varchar(60) DEFAULT NULL COMMENT '프로그램한글명',
  `PROGRM_DC` varchar(200) DEFAULT NULL COMMENT '프로그램설명',
  `URL` varchar(100) NOT NULL COMMENT 'URL'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='프로그램목록';


-- ippado.IPD_ROLE definition

CREATE TABLE `IPD_ROLE` (
  `ROLE_CODE` varchar(50) NOT NULL DEFAULT '' COMMENT '롤코드',
  `ROLE_NM` varchar(60) NOT NULL COMMENT '롤명',
  `ROLE_PTTRN` varchar(300) DEFAULT NULL COMMENT '롤패턴',
  `ROLE_DC` varchar(200) DEFAULT NULL COMMENT '롤설명',
  `ROLE_TY` varchar(80) DEFAULT NULL COMMENT '롤유형',
  `ROLE_SORT` varchar(10) DEFAULT NULL COMMENT '롤정렬',
  `ROLE_CREAT_DE` char(20) NOT NULL COMMENT '롤생성일',
  PRIMARY KEY (`ROLE_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='롤정보';


-- ippado.IPD_WSF_CUSTOMER definition

CREATE TABLE `IPD_WSF_CUSTOMER` (
  `CSTMR_ID` varchar(20) NOT NULL COMMENT '고객ID',
  `CSTMR_NM` varchar(50) NOT NULL COMMENT '고객명',
  `SEXDSTN` char(1) DEFAULT NULL COMMENT '성별',
  `BRTHDY` char(8) DEFAULT NULL COMMENT '생년월일',
  `CTTPC` varchar(20) NOT NULL COMMENT '연락처',
  `REMARK` varchar(1000) DEFAULT NULL COMMENT '메모',
  `FRST_REGIST_PNTTM` datetime DEFAULT NULL COMMENT '최초등록일시',
  `FRST_REGISTER_ID` varchar(20) DEFAULT NULL COMMENT '등록자',
  `LAST_UPDT_PNTTM` datetime DEFAULT NULL COMMENT '마지막수정일시',
  `LAST_UPDUSR_ID` varchar(20) DEFAULT NULL COMMENT '수정자',
  PRIMARY KEY (`CSTMR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='서해도선 고객관리';


-- ippado.IPD_WSF_EMBARKATION definition

CREATE TABLE `IPD_WSF_EMBARKATION` (
  `EMBRK_ID` varchar(20) NOT NULL COMMENT '승선ID',
  `NVG_ID` varchar(20) NOT NULL COMMENT '운항ID',
  `CHRGE_ID` varchar(20) NOT NULL COMMENT '요금ID',
  `GRP_YN` char(1) DEFAULT NULL COMMENT '그룹여부',
  `CHIL_YN` char(1) DEFAULT NULL COMMENT '소인여부',
  `INHBTNT_YN` varchar(1) DEFAULT NULL COMMENT '주민여부',
  `PYMNTMNY` int(10) DEFAULT NULL COMMENT '지불금',
  `PRNTNG_YN` char(1) DEFAULT NULL COMMENT '출력여부',
  `FRST_REGIST_PNTTM` datetime DEFAULT NULL COMMENT '최초등록일시',
  `FRST_REGISTER_ID` varchar(20) DEFAULT NULL COMMENT '등록자',
  `LAST_UPDT_PNTTM` datetime DEFAULT NULL COMMENT '마지막수정일시',
  `LAST_UPDUSR_ID` varchar(20) DEFAULT NULL COMMENT '수정자',
  PRIMARY KEY (`EMBRK_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='서해도선 승선관리';


-- ippado.IPD_WSF_NAVIGATION definition

CREATE TABLE `IPD_WSF_NAVIGATION` (
  `NVG_ID` varchar(20) NOT NULL COMMENT '운항ID',
  `START_PORT` varchar(6) DEFAULT NULL COMMENT '출발항',
  `ARVL_PORT` varchar(6) DEFAULT NULL COMMENT '도착항',
  `START_DT` datetime DEFAULT NULL COMMENT '출발일시',
  `NVG_DIV` varchar(6) DEFAULT NULL COMMENT '운항구분',
  `FRST_REGIST_PNTTM` datetime DEFAULT NULL COMMENT '최초등록일시',
  `FRST_REGISTER_ID` varchar(20) DEFAULT NULL COMMENT '등록자',
  `LAST_UPDT_PNTTM` datetime DEFAULT NULL COMMENT '마지막수정일시',
  `LAST_UPDUSR_ID` varchar(20) DEFAULT NULL COMMENT '수정자',
  PRIMARY KEY (`NVG_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='서해도선 운항관리';


-- ippado.LETTNBBSMASTER definition

CREATE TABLE `LETTNBBSMASTER` (
  `BBS_ID` char(20) NOT NULL COMMENT '게시판ID',
  `BBS_NM` varchar(255) NOT NULL COMMENT '게시판명',
  `BBS_INTRCN` varchar(2400) DEFAULT NULL COMMENT '게시판소개',
  `BBS_TY_CODE` char(6) NOT NULL COMMENT '게시판유형코드',
  `BBS_ATTRB_CODE` char(6) NOT NULL,
  `REPLY_POSBL_AT` char(1) DEFAULT NULL COMMENT '답장가능여부',
  `FILE_ATCH_POSBL_AT` char(1) NOT NULL COMMENT '파일첨부가능여부',
  `ATCH_POSBL_FILE_NUMBER` decimal(2,0) NOT NULL COMMENT '첨부가능파일숫자',
  `ATCH_POSBL_FILE_SIZE` decimal(8,0) DEFAULT NULL COMMENT '첨부가능파일사이즈',
  `USE_AT` char(1) NOT NULL COMMENT '사용여부',
  `TMPLAT_ID` char(20) DEFAULT NULL COMMENT '템플릿ID',
  `FRST_REGISTER_ID` varchar(20) NOT NULL COMMENT '최초등록자ID',
  `FRST_REGIST_PNTTM` datetime NOT NULL COMMENT '최초등록시점',
  `LAST_UPDUSR_ID` varchar(20) DEFAULT NULL COMMENT '최종수정자ID',
  `LAST_UPDT_PNTTM` datetime DEFAULT NULL COMMENT '최종수정시점',
  PRIMARY KEY (`BBS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='게시판마스터';


-- ippado.LETTNBBSMASTEROPTN definition

CREATE TABLE `LETTNBBSMASTEROPTN` (
  `BBS_ID` char(20) NOT NULL COMMENT '게시판ID',
  `ANSWER_AT` char(1) NOT NULL COMMENT '댓글여부',
  `STSFDG_AT` char(1) NOT NULL COMMENT '만족도여부',
  `FRST_REGIST_PNTTM` datetime NOT NULL COMMENT '최초등록시점',
  `LAST_UPDT_PNTTM` datetime DEFAULT NULL COMMENT '최종수정시점',
  `FRST_REGISTER_ID` varchar(20) NOT NULL COMMENT '최초등록자ID',
  `LAST_UPDUSR_ID` varchar(20) DEFAULT NULL COMMENT '최종수정자ID',
  PRIMARY KEY (`BBS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='게시판마스터옵션';


-- ippado.LETTNFILE definition

CREATE TABLE `LETTNFILE` (
  `ATCH_FILE_ID` char(20) NOT NULL COMMENT '첨부파일ID',
  `CREAT_DT` datetime NOT NULL COMMENT '생성일시',
  `USE_AT` char(1) DEFAULT NULL COMMENT '사용여부',
  PRIMARY KEY (`ATCH_FILE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='파일속성';


-- ippado.LETTNSYSLOG definition

CREATE TABLE `LETTNSYSLOG` (
  `REQUST_ID` varchar(20) NOT NULL COMMENT '요청ID',
  `JOB_SE_CODE` char(3) DEFAULT NULL COMMENT '업무구분코드',
  `INSTT_CODE` char(7) DEFAULT NULL COMMENT '기관코드',
  `OCCRRNC_DE` datetime DEFAULT NULL COMMENT '발생일',
  `RQESTER_IP` varchar(23) DEFAULT NULL COMMENT '요청자IP',
  `RQESTER_ID` varchar(20) DEFAULT NULL COMMENT '요청자ID',
  `TRGET_MENU_NM` varchar(255) DEFAULT NULL COMMENT '대상메뉴명',
  `SVC_NM` varchar(255) DEFAULT NULL COMMENT '서비스명',
  `METHOD_NM` varchar(60) DEFAULT NULL COMMENT '메서드명',
  `PROCESS_SE_CODE` char(3) DEFAULT NULL COMMENT '처리구분코드',
  `PROCESS_CO` decimal(10,0) DEFAULT NULL COMMENT '처리수',
  `PROCESS_TIME` varchar(14) DEFAULT NULL COMMENT '처리시간',
  `RSPNS_CODE` char(3) DEFAULT NULL COMMENT '응답코드',
  `ERROR_SE` char(1) DEFAULT NULL COMMENT '오류구분',
  `ERROR_CO` decimal(10,0) DEFAULT NULL COMMENT '오류수',
  `ERROR_CODE` char(3) DEFAULT NULL COMMENT '오류코드',
  PRIMARY KEY (`REQUST_ID`),
  UNIQUE KEY `LETTNSYSLOG_PK` (`REQUST_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- ippado.LETTNSYSLOGSUMMARY definition

CREATE TABLE `LETTNSYSLOGSUMMARY` (
  `OCCRRNC_DE` char(8) NOT NULL COMMENT '발생일',
  `SRVC_NM` varchar(255) NOT NULL,
  `METHOD_NM` varchar(60) NOT NULL COMMENT '메서드명',
  `CREAT_CO` decimal(10,0) DEFAULT NULL COMMENT '생성수',
  `UPDT_CO` decimal(10,0) DEFAULT NULL COMMENT '수정수',
  `RDCNT` decimal(10,0) DEFAULT NULL COMMENT '조회수',
  `DELETE_CO` decimal(10,0) DEFAULT NULL COMMENT '삭제수',
  `OUTPT_CO` decimal(10,0) DEFAULT NULL COMMENT '출력수',
  `ERROR_CO` decimal(10,0) DEFAULT NULL COMMENT '오류수',
  PRIMARY KEY (`OCCRRNC_DE`,`SRVC_NM`,`METHOD_NM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='시스템로그요약';


-- ippado.LETTNTMPLATINFO definition

CREATE TABLE `LETTNTMPLATINFO` (
  `TMPLAT_ID` char(20) NOT NULL DEFAULT '' COMMENT '템플릿ID',
  `TMPLAT_NM` varchar(255) DEFAULT NULL COMMENT '템플릿명',
  `TMPLAT_COURS` varchar(2000) DEFAULT NULL COMMENT '템플릿경로',
  `USE_AT` char(1) DEFAULT NULL COMMENT '사용여부',
  `TMPLAT_SE_CODE` char(6) DEFAULT NULL COMMENT '템플릿구분코드',
  `FRST_REGISTER_ID` varchar(20) DEFAULT NULL COMMENT '최초등록자ID',
  `FRST_REGIST_PNTTM` datetime DEFAULT NULL COMMENT '최초등록시점',
  `LAST_UPDUSR_ID` varchar(20) DEFAULT NULL COMMENT '최종수정자ID',
  `LAST_UPDT_PNTTM` datetime DEFAULT NULL COMMENT '최종수정시점',
  PRIMARY KEY (`TMPLAT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='템플릿';


-- ippado.LETTNUSERABSNCE definition

CREATE TABLE `LETTNUSERABSNCE` (
  `USER_ID` varchar(20) NOT NULL DEFAULT '' COMMENT '사용자ID',
  `USER_ABSNCE_AT` char(1) NOT NULL COMMENT '사용자부재여부',
  `FRST_REGISTER_ID` varchar(20) DEFAULT NULL COMMENT '최초등록자ID',
  `FRST_REGIST_PNTTM` datetime DEFAULT NULL COMMENT '최초등록시점',
  `LAST_UPDUSR_ID` varchar(20) DEFAULT NULL COMMENT '최종수정자ID',
  `LAST_UPDT_PNTTM` datetime DEFAULT NULL COMMENT '최종수정시점',
  PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='사용자부재';


-- ippado.IPD_AUTHOR_ROLE definition

CREATE TABLE `IPD_AUTHOR_ROLE` (
  `AUTHOR_CODE` varchar(30) NOT NULL COMMENT '권한코드',
  `ROLE_CODE` varchar(50) NOT NULL COMMENT '롤코드',
  `CREAT_DT` datetime DEFAULT NULL COMMENT '생성일시',
  PRIMARY KEY (`AUTHOR_CODE`,`ROLE_CODE`),
  KEY `R_292` (`ROLE_CODE`),
  CONSTRAINT `IPD_AUTHOR_ROLE_ibfk_1` FOREIGN KEY (`AUTHOR_CODE`) REFERENCES `IPD_AUTHOR` (`AUTHOR_CODE`) ON DELETE CASCADE,
  CONSTRAINT `IPD_AUTHOR_ROLE_ibfk_2` FOREIGN KEY (`ROLE_CODE`) REFERENCES `IPD_ROLE` (`ROLE_CODE`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='권한롤관계';


-- ippado.IPD_CODE definition

CREATE TABLE `IPD_CODE` (
  `CODE_ID` varchar(6) NOT NULL COMMENT '코드ID',
  `CODE_ID_NM` varchar(60) DEFAULT NULL COMMENT '코드ID명',
  `CODE_ID_DC` varchar(200) DEFAULT NULL COMMENT '코드ID설명',
  `USE_AT` char(1) DEFAULT NULL COMMENT '사용여부',
  `CL_CODE` char(3) DEFAULT NULL COMMENT '분류코드',
  `FRST_REGIST_PNTTM` datetime DEFAULT NULL COMMENT '최초등록시점',
  `FRST_REGISTER_ID` varchar(20) DEFAULT NULL COMMENT '최초등록자ID',
  `LAST_UPDT_PNTTM` datetime DEFAULT NULL COMMENT '최종수정시점',
  `LAST_UPDUSR_ID` varchar(20) DEFAULT NULL COMMENT '최종수정자ID',
  PRIMARY KEY (`CODE_ID`),
  KEY `R_179` (`CL_CODE`),
  CONSTRAINT `IPD_CODE_ibfk_1` FOREIGN KEY (`CL_CODE`) REFERENCES `IPD_CL_CODE` (`CL_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='공통코드';


-- ippado.IPD_DETAIL_CODE definition

CREATE TABLE `IPD_DETAIL_CODE` (
  `CODE_ID` varchar(6) NOT NULL COMMENT '코드ID',
  `CODE` varchar(15) NOT NULL COMMENT '코드',
  `CODE_NM` varchar(60) DEFAULT NULL COMMENT '코드명',
  `CODE_DC` varchar(200) DEFAULT NULL COMMENT '코드설명',
  `USE_AT` char(1) DEFAULT NULL COMMENT '사용여부',
  `FRST_REGIST_PNTTM` datetime DEFAULT NULL COMMENT '최초등록시점',
  `FRST_REGISTER_ID` varchar(20) DEFAULT NULL COMMENT '최초등록자ID',
  `LAST_UPDT_PNTTM` datetime DEFAULT NULL COMMENT '최종수정시점',
  `LAST_UPDUSR_ID` varchar(20) DEFAULT NULL COMMENT '최종수정자ID',
  PRIMARY KEY (`CODE_ID`,`CODE`),
  CONSTRAINT `IPD_DETAIL_CODE_ibfk_1` FOREIGN KEY (`CODE_ID`) REFERENCES `IPD_CODE` (`CODE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='공통상세코드';


-- ippado.IPD_MBER definition

CREATE TABLE `IPD_MBER` (
  `USER_ID` varchar(20) NOT NULL COMMENT '업무사용자ID',
  `USER_NM` varchar(60) NOT NULL COMMENT '사용자명',
  `PASSWORD` varchar(200) NOT NULL COMMENT '비밀번호',
  `MBTLNUM` varchar(20) DEFAULT NULL COMMENT '모바일번호',
  `EMAIL_ADRES` varchar(50) DEFAULT NULL COMMENT '이메일주소',
  `GROUP_ID` char(20) DEFAULT NULL COMMENT '그룹ID',
  `USER_STTUS_CODE` char(1) NOT NULL COMMENT '사용자상태코드',
  `SBSCR_DE` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`USER_ID`),
  KEY `LETTNEMPLYRINFO_ibfk_2` (`GROUP_ID`),
  CONSTRAINT `IPD_MBER_ibfk_2` FOREIGN KEY (`GROUP_ID`) REFERENCES `IPD_GROUP` (`GROUP_ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='업무사용자정보';


-- ippado.IPD_MBER_AUTHOR definition

CREATE TABLE `IPD_MBER_AUTHOR` (
  `SCRTY_DTRMN_TRGET_ID` varchar(20) NOT NULL COMMENT '보안설정대상ID',
  `MBER_TY_CODE` char(5) DEFAULT NULL COMMENT '회원유형코드',
  `AUTHOR_CODE` varchar(30) NOT NULL COMMENT '권한코드',
  PRIMARY KEY (`SCRTY_DTRMN_TRGET_ID`),
  KEY `LETTNEMPLYRSCRTYESTBS_ibfk_4` (`AUTHOR_CODE`),
  CONSTRAINT `IPD_MBER_AUTHOR_ibfk_4` FOREIGN KEY (`AUTHOR_CODE`) REFERENCES `IPD_AUTHOR` (`AUTHOR_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='사용자보안설정';


-- ippado.IPD_MENUS definition

CREATE TABLE `IPD_MENUS` (
  `MENU_NM` varchar(60) NOT NULL COMMENT '메뉴명',
  `PROGRM_FILE_NM` varchar(60) NOT NULL COMMENT '프로그램파일명',
  `MENU_NO` decimal(20,0) NOT NULL COMMENT '메뉴번호',
  `UPPER_MENU_NO` decimal(20,0) DEFAULT NULL COMMENT '상위메뉴번호',
  `MENU_ORDR` decimal(5,0) NOT NULL COMMENT '메뉴순서',
  `MENU_DC` varchar(250) DEFAULT NULL COMMENT '메뉴설명',
  `RELATE_IMAGE_PATH` varchar(100) DEFAULT NULL COMMENT '관계이미지경로',
  `RELATE_IMAGE_NM` varchar(60) DEFAULT NULL COMMENT '관계이미지명',
  PRIMARY KEY (`MENU_NO`),
  KEY `R_2` (`PROGRM_FILE_NM`),
  KEY `R_4` (`UPPER_MENU_NO`),
  CONSTRAINT `IPD_MENUS_ibfk_2` FOREIGN KEY (`UPPER_MENU_NO`) REFERENCES `IPD_MENUS` (`MENU_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='메뉴정보';


-- ippado.IPD_MENU_AUTHOR definition

CREATE TABLE `IPD_MENU_AUTHOR` (
  `MENU_NO` decimal(20,0) NOT NULL COMMENT '메뉴번호',
  `AUTHOR_CODE` varchar(30) NOT NULL COMMENT '권한코드',
  `MAPNG_CREAT_ID` varchar(30) DEFAULT NULL COMMENT '매핑생성ID',
  PRIMARY KEY (`MENU_NO`,`AUTHOR_CODE`),
  KEY `R_247` (`MAPNG_CREAT_ID`),
  KEY `R_303` (`AUTHOR_CODE`),
  CONSTRAINT `IPD_MENU_AUTHOR_ibfk_1` FOREIGN KEY (`MENU_NO`) REFERENCES `IPD_MENUS` (`MENU_NO`) ON DELETE CASCADE,
  CONSTRAINT `IPD_MENU_AUTHOR_ibfk_3` FOREIGN KEY (`AUTHOR_CODE`) REFERENCES `IPD_AUTHOR` (`AUTHOR_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='메뉴생성내역';


-- ippado.IPD_ROLES_HIERARCHY definition

CREATE TABLE `IPD_ROLES_HIERARCHY` (
  `PARNTS_ROLE` varchar(30) NOT NULL COMMENT '부모롤',
  `CHLDRN_ROLE` varchar(30) NOT NULL COMMENT '자식롤',
  PRIMARY KEY (`PARNTS_ROLE`,`CHLDRN_ROLE`),
  KEY `R_308` (`CHLDRN_ROLE`),
  CONSTRAINT `IPD_ROLES_HIERARCHY_ibfk_1` FOREIGN KEY (`PARNTS_ROLE`) REFERENCES `IPD_AUTHOR` (`AUTHOR_CODE`) ON DELETE CASCADE,
  CONSTRAINT `IPD_ROLES_HIERARCHY_ibfk_2` FOREIGN KEY (`CHLDRN_ROLE`) REFERENCES `IPD_AUTHOR` (`AUTHOR_CODE`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='롤 계층구조';


-- ippado.LETTNBBS definition

CREATE TABLE `LETTNBBS` (
  `NTT_ID` decimal(20,0) NOT NULL COMMENT '게시물ID',
  `BBS_ID` char(20) NOT NULL COMMENT '게시판ID',
  `NTT_NO` decimal(20,0) DEFAULT NULL COMMENT '게시물번호',
  `NTT_SJ` varchar(2000) DEFAULT NULL COMMENT '게시물제목',
  `NTT_CN` mediumtext DEFAULT NULL COMMENT '게시물내용',
  `ANSWER_AT` char(1) DEFAULT NULL COMMENT '댓글여부',
  `PARNTSCTT_NO` decimal(10,0) DEFAULT NULL COMMENT '부모글번호',
  `ANSWER_LC` decimal(8,0) DEFAULT NULL COMMENT '댓글위치',
  `SORT_ORDR` decimal(8,0) DEFAULT NULL COMMENT '정렬순서',
  `RDCNT` decimal(10,0) DEFAULT NULL COMMENT '조회수',
  `USE_AT` char(1) NOT NULL COMMENT '사용여부',
  `NTCE_BGNDE` char(20) DEFAULT NULL COMMENT '게시시작일',
  `NTCE_ENDDE` char(20) DEFAULT NULL COMMENT '게시종료일',
  `NTCR_ID` varchar(20) DEFAULT NULL COMMENT '게시자ID',
  `NTCR_NM` varchar(20) DEFAULT NULL COMMENT '게시자명',
  `PASSWORD` varchar(200) DEFAULT NULL COMMENT '비밀번호',
  `ATCH_FILE_ID` char(20) DEFAULT NULL COMMENT '첨부파일ID',
  `FRST_REGIST_PNTTM` datetime NOT NULL COMMENT '최초등록시점',
  `FRST_REGISTER_ID` varchar(20) NOT NULL COMMENT '최초등록자ID',
  `LAST_UPDT_PNTTM` datetime DEFAULT NULL COMMENT '최종수정시점',
  `LAST_UPDUSR_ID` varchar(20) DEFAULT NULL COMMENT '최종수정자ID',
  PRIMARY KEY (`NTT_ID`,`BBS_ID`),
  KEY `LETTNBBS_ibfk_1` (`BBS_ID`),
  CONSTRAINT `LETTNBBS_ibfk_1` FOREIGN KEY (`BBS_ID`) REFERENCES `LETTNBBSMASTER` (`BBS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='게시판';


-- ippado.LETTNBBSUSE definition

CREATE TABLE `LETTNBBSUSE` (
  `BBS_ID` char(20) NOT NULL COMMENT '게시판ID',
  `TRGET_ID` char(20) NOT NULL DEFAULT '' COMMENT '대상ID',
  `USE_AT` char(1) NOT NULL COMMENT '사용여부',
  `REGIST_SE_CODE` char(6) DEFAULT NULL COMMENT '등록구분코드',
  `FRST_REGIST_PNTTM` datetime DEFAULT NULL COMMENT '최초등록시점',
  `FRST_REGISTER_ID` varchar(20) NOT NULL COMMENT '최초등록자ID',
  `LAST_UPDT_PNTTM` datetime DEFAULT NULL COMMENT '최종수정시점',
  `LAST_UPDUSR_ID` varchar(20) DEFAULT NULL COMMENT '최종수정자ID',
  PRIMARY KEY (`BBS_ID`,`TRGET_ID`),
  CONSTRAINT `LETTNBBSUSE_ibfk_1` FOREIGN KEY (`BBS_ID`) REFERENCES `LETTNBBSMASTER` (`BBS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='게시판활용';


-- ippado.LETTNFILEDETAIL definition

CREATE TABLE `LETTNFILEDETAIL` (
  `ATCH_FILE_ID` char(20) NOT NULL COMMENT '첨부파일ID',
  `FILE_SN` decimal(10,0) NOT NULL COMMENT '파일순번',
  `FILE_STRE_COURS` varchar(2000) NOT NULL COMMENT '파일저장경로',
  `STRE_FILE_NM` varchar(255) NOT NULL COMMENT '저장파일명',
  `ORIGNL_FILE_NM` varchar(255) DEFAULT NULL COMMENT '원파일명',
  `FILE_EXTSN` varchar(20) NOT NULL COMMENT '파일확장자',
  `FILE_CN` mediumtext DEFAULT NULL COMMENT '파일내용',
  `FILE_SIZE` decimal(8,0) DEFAULT NULL COMMENT '파일크기',
  PRIMARY KEY (`ATCH_FILE_ID`,`FILE_SN`),
  CONSTRAINT `LETTNFILEDETAIL_ibfk_1` FOREIGN KEY (`ATCH_FILE_ID`) REFERENCES `LETTNFILE` (`ATCH_FILE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='파일상세정보';